# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adminWindow(object):
    def setupUi(self, adminWindow):
        adminWindow.setObjectName("adminWindow")
        adminWindow.resize(362, 494)
        self.add_groupBox = QtWidgets.QGroupBox(adminWindow)
        self.add_groupBox.setGeometry(QtCore.QRect(20, 20, 321, 161))
        self.add_groupBox.setObjectName("add_groupBox")
        self.name_label = QtWidgets.QLabel(self.add_groupBox)
        self.name_label.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.name_label.setObjectName("name_label")
        self.attribute_label = QtWidgets.QLabel(self.add_groupBox)
        self.attribute_label.setGeometry(QtCore.QRect(20, 80, 72, 15))
        self.attribute_label.setObjectName("attribute_label")
        self.attribute_lineEdit = QtWidgets.QLineEdit(self.add_groupBox)
        self.attribute_lineEdit.setGeometry(QtCore.QRect(100, 77, 201, 21))
        self.attribute_lineEdit.setObjectName("attribute_lineEdit")
        self.explain1_label = QtWidgets.QLabel(self.add_groupBox)
        self.explain1_label.setGeometry(QtCore.QRect(20, 120, 201, 16))
        self.explain1_label.setObjectName("explain1_label")
        self.add_pushButton = QtWidgets.QPushButton(self.add_groupBox)
        self.add_pushButton.setGeometry(QtCore.QRect(220, 113, 81, 28))
        self.add_pushButton.setObjectName("add_pushButton")
        self.name_lineEdit = QtWidgets.QLineEdit(self.add_groupBox)
        self.name_lineEdit.setGeometry(QtCore.QRect(100, 37, 201, 21))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.delete_groupBox = QtWidgets.QGroupBox(adminWindow)
        self.delete_groupBox.setGeometry(QtCore.QRect(20, 190, 321, 121))
        self.delete_groupBox.setObjectName("delete_groupBox")
        self.sort_comboBox = QtWidgets.QComboBox(self.delete_groupBox)
        self.sort_comboBox.setGeometry(QtCore.QRect(100, 37, 201, 22))
        self.sort_comboBox.setObjectName("sort_comboBox")
        self.sort_label = QtWidgets.QLabel(self.delete_groupBox)
        self.sort_label.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.sort_label.setObjectName("sort_label")
        self.delete_pushButton = QtWidgets.QPushButton(self.delete_groupBox)
        self.delete_pushButton.setGeometry(QtCore.QRect(220, 73, 81, 28))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.explain2_label = QtWidgets.QLabel(self.delete_groupBox)
        self.explain2_label.setGeometry(QtCore.QRect(20, 80, 201, 16))
        self.explain2_label.setObjectName("explain2_label")
        self.back_pushButton = QtWidgets.QPushButton(adminWindow)
        self.back_pushButton.setGeometry(QtCore.QRect(20, 450, 321, 28))
        self.back_pushButton.setObjectName("back_pushButton")
        self.groupBox = QtWidgets.QGroupBox(adminWindow)
        self.groupBox.setGeometry(QtCore.QRect(20, 320, 321, 121))
        self.groupBox.setObjectName("groupBox")
        self.userName_label = QtWidgets.QLabel(self.groupBox)
        self.userName_label.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.userName_label.setObjectName("userName_label")
        self.userName_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.userName_comboBox.setGeometry(QtCore.QRect(100, 37, 201, 22))
        self.userName_comboBox.setObjectName("userName_comboBox")
        self.findUser_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.findUser_pushButton.setGeometry(QtCore.QRect(20, 80, 131, 28))
        self.findUser_pushButton.setObjectName("findUser_pushButton")
        self.deleteUser_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.deleteUser_pushButton.setGeometry(QtCore.QRect(170, 80, 131, 28))
        self.deleteUser_pushButton.setObjectName("deleteUser_pushButton")

        self.retranslateUi(adminWindow)
        QtCore.QMetaObject.connectSlotsByName(adminWindow)

    def retranslateUi(self, adminWindow):
        _translate = QtCore.QCoreApplication.translate
        adminWindow.setWindowTitle(_translate("adminWindow", "Form"))
        self.add_groupBox.setTitle(_translate("adminWindow", "添加区"))
        self.name_label.setText(_translate("adminWindow", "种类名称"))
        self.attribute_label.setText(_translate("adminWindow", "增添属性"))
        self.explain1_label.setText(_translate("adminWindow", "说明：属性间请以空格间隔！"))
        self.add_pushButton.setText(_translate("adminWindow", "添加"))
        self.delete_groupBox.setTitle(_translate("adminWindow", "删除区"))
        self.sort_label.setText(_translate("adminWindow", "增添属性"))
        self.delete_pushButton.setText(_translate("adminWindow", "删除"))
        self.explain2_label.setText(_translate("adminWindow", "说明：会将数据一并删除！"))
        self.back_pushButton.setText(_translate("adminWindow", "返回"))
        self.groupBox.setTitle(_translate("adminWindow", "账号管理"))
        self.userName_label.setText(_translate("adminWindow", "用户名"))
        self.findUser_pushButton.setText(_translate("adminWindow", "查找"))
        self.deleteUser_pushButton.setText(_translate("adminWindow", "删除"))
