# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.add_groupBox.setGeometry(QtCore.QRect(30, 20, 481, 181))
        self.add_groupBox.setObjectName("add_groupBox")
        self.addName_lineEdit = QtWidgets.QLineEdit(self.add_groupBox)
        self.addName_lineEdit.setGeometry(QtCore.QRect(80, 40, 151, 21))
        self.addName_lineEdit.setObjectName("addName_lineEdit")
        self.addName_label = QtWidgets.QLabel(self.add_groupBox)
        self.addName_label.setGeometry(QtCore.QRect(20, 45, 72, 15))
        self.addName_label.setObjectName("addName_label")
        self.addDesc_label = QtWidgets.QLabel(self.add_groupBox)
        self.addDesc_label.setGeometry(QtCore.QRect(20, 95, 72, 15))
        self.addDesc_label.setObjectName("addDesc_label")
        self.addInfo_label = QtWidgets.QLabel(self.add_groupBox)
        self.addInfo_label.setGeometry(QtCore.QRect(250, 90, 72, 31))
        self.addInfo_label.setObjectName("addInfo_label")
        self.add_pushButton = QtWidgets.QPushButton(self.add_groupBox)
        self.add_pushButton.setGeometry(QtCore.QRect(250, 35, 211, 28))
        self.add_pushButton.setObjectName("add_pushButton")
        self.addDesc_textEdit = QtWidgets.QTextEdit(self.add_groupBox)
        self.addDesc_textEdit.setGeometry(QtCore.QRect(80, 90, 151, 61))
        self.addDesc_textEdit.setObjectName("addDesc_textEdit")
        self.addInfo_textEdit = QtWidgets.QTextEdit(self.add_groupBox)
        self.addInfo_textEdit.setGeometry(QtCore.QRect(310, 90, 151, 61))
        self.addInfo_textEdit.setObjectName("addInfo_textEdit")
        self.list_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.list_groupBox.setGeometry(QtCore.QRect(30, 220, 1051, 521))
        self.list_groupBox.setObjectName("list_groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.list_groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 1011, 471))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(820, 20, 261, 181))
        self.groupBox.setObjectName("groupBox")
        self.findAll_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.findAll_pushButton.setGeometry(QtCore.QRect(20, 35, 221, 28))
        self.findAll_pushButton.setObjectName("findAll_pushButton")
        self.findName_label = QtWidgets.QLabel(self.groupBox)
        self.findName_label.setGeometry(QtCore.QRect(20, 90, 72, 31))
        self.findName_label.setObjectName("findName_label")
        self.findName_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.findName_comboBox.setGeometry(QtCore.QRect(80, 90, 161, 22))
        self.findName_comboBox.setObjectName("findName_comboBox")
        self.findKeyWord_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.findKeyWord_pushButton.setGeometry(QtCore.QRect(10, 140, 221, 28))
        self.findKeyWord_pushButton.setObjectName("findKeyWord_pushButton")
        self.sort_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sort_comboBox.setGeometry(QtCore.QRect(550, 50, 161, 22))
        self.sort_comboBox.setObjectName("sort_comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_groupBox.setTitle(_translate("MainWindow", "添加区"))
        self.addName_label.setText(_translate("MainWindow", "名称"))
        self.addDesc_label.setText(_translate("MainWindow", "描述"))
        self.addInfo_label.setText(_translate("MainWindow", "联系人\n"
"信息"))
        self.add_pushButton.setText(_translate("MainWindow", "添加"))
        self.list_groupBox.setTitle(_translate("MainWindow", "物品列表"))
        self.groupBox.setTitle(_translate("MainWindow", "查找区"))
        self.findAll_pushButton.setText(_translate("MainWindow", "查看全部"))
        self.findName_label.setText(_translate("MainWindow", "查找\n"
"物品"))
        self.findKeyWord_pushButton.setText(_translate("MainWindow", "查找"))
