# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.add_groupBox.setGeometry(QtCore.QRect(30, 20, 1061, 81))
        self.add_groupBox.setObjectName("add_groupBox")
        self.sort_comboBox = QtWidgets.QComboBox(self.add_groupBox)
        self.sort_comboBox.setGeometry(QtCore.QRect(110, 33, 141, 22))
        self.sort_comboBox.setObjectName("sort_comboBox")
        self.sort_label = QtWidgets.QLabel(self.add_groupBox)
        self.sort_label.setGeometry(QtCore.QRect(30, 30, 72, 31))
        self.sort_label.setObjectName("sort_label")
        self.findKeyWord_pushButton = QtWidgets.QPushButton(self.add_groupBox)
        self.findKeyWord_pushButton.setGeometry(QtCore.QRect(890, 30, 141, 28))
        self.findKeyWord_pushButton.setObjectName("findKeyWord_pushButton")
        self.add_pushButton = QtWidgets.QPushButton(self.add_groupBox)
        self.add_pushButton.setGeometry(QtCore.QRect(270, 30, 141, 28))
        self.add_pushButton.setObjectName("add_pushButton")
        self.findAll_pushButton = QtWidgets.QPushButton(self.add_groupBox)
        self.findAll_pushButton.setGeometry(QtCore.QRect(430, 30, 141, 28))
        self.findAll_pushButton.setObjectName("findAll_pushButton")
        self.findKeyWord_lineEdit = QtWidgets.QLineEdit(self.add_groupBox)
        self.findKeyWord_lineEdit.setGeometry(QtCore.QRect(680, 33, 191, 21))
        self.findKeyWord_lineEdit.setObjectName("findKeyWord_lineEdit")
        self.findKeyWord_label = QtWidgets.QLabel(self.add_groupBox)
        self.findKeyWord_label.setGeometry(QtCore.QRect(590, 30, 81, 31))
        self.findKeyWord_label.setObjectName("findKeyWord_label")
        self.list_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.list_groupBox.setGeometry(QtCore.QRect(30, 120, 1061, 601))
        self.list_groupBox.setObjectName("list_groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.list_groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 1021, 551))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        self.quit_menu = QtWidgets.QMenu(self.menubar)
        self.quit_menu.setObjectName("quit_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.quitAction = QtWidgets.QAction(MainWindow)
        self.quitAction.setObjectName("quitAction")
        self.adminAction = QtWidgets.QAction(MainWindow)
        self.adminAction.setObjectName("adminAction")
        self.helpAction = QtWidgets.QAction(MainWindow)
        self.helpAction.setObjectName("helpAction")
        self.quit_menu.addAction(self.quitAction)
        self.quit_menu.addAction(self.adminAction)
        self.quit_menu.addAction(self.helpAction)
        self.menubar.addAction(self.quit_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_groupBox.setTitle(_translate("MainWindow", "操作区"))
        self.sort_label.setText(_translate("MainWindow", "物品种类"))
        self.findKeyWord_pushButton.setText(_translate("MainWindow", "查找"))
        self.add_pushButton.setText(_translate("MainWindow", "添加"))
        self.findAll_pushButton.setText(_translate("MainWindow", "查看全部"))
        self.findKeyWord_label.setText(_translate("MainWindow", "关键字查找"))
        self.list_groupBox.setTitle(_translate("MainWindow", "物品列表"))
        self.quit_menu.setTitle(_translate("MainWindow", "更多操作"))
        self.quitAction.setText(_translate("MainWindow", "退出登录"))
        self.adminAction.setText(_translate("MainWindow", "管理员选项"))
        self.helpAction.setText(_translate("MainWindow", "帮助"))
