# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(400, 466)
        self.confirm_pushButton = QtWidgets.QPushButton(RegisterWindow)
        self.confirm_pushButton.setGeometry(QtCore.QRect(220, 400, 131, 28))
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.userName_label = QtWidgets.QLabel(RegisterWindow)
        self.userName_label.setGeometry(QtCore.QRect(50, 50, 72, 15))
        self.userName_label.setObjectName("userName_label")
        self.userName_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.userName_lineEdit.setGeometry(QtCore.QRect(120, 45, 231, 21))
        self.userName_lineEdit.setObjectName("userName_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.password_lineEdit.setGeometry(QtCore.QRect(120, 95, 231, 21))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.cancel_pushButton = QtWidgets.QPushButton(RegisterWindow)
        self.cancel_pushButton.setGeometry(QtCore.QRect(50, 400, 131, 28))
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.password_label = QtWidgets.QLabel(RegisterWindow)
        self.password_label.setGeometry(QtCore.QRect(50, 100, 72, 15))
        self.password_label.setObjectName("password_label")
        self.repassword_label = QtWidgets.QLabel(RegisterWindow)
        self.repassword_label.setGeometry(QtCore.QRect(45, 150, 72, 15))
        self.repassword_label.setObjectName("repassword_label")
        self.repassword_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.repassword_lineEdit.setGeometry(QtCore.QRect(120, 145, 231, 21))
        self.repassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repassword_lineEdit.setObjectName("repassword_lineEdit")
        self.adress_label = QtWidgets.QLabel(RegisterWindow)
        self.adress_label.setGeometry(QtCore.QRect(50, 200, 72, 15))
        self.adress_label.setObjectName("adress_label")
        self.adress_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.adress_lineEdit.setGeometry(QtCore.QRect(120, 195, 231, 21))
        self.adress_lineEdit.setObjectName("adress_lineEdit")
        self.phone_label = QtWidgets.QLabel(RegisterWindow)
        self.phone_label.setGeometry(QtCore.QRect(45, 250, 72, 15))
        self.phone_label.setObjectName("phone_label")
        self.phone_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.phone_lineEdit.setGeometry(QtCore.QRect(120, 245, 231, 21))
        self.phone_lineEdit.setObjectName("phone_lineEdit")
        self.aduserName_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.aduserName_lineEdit.setGeometry(QtCore.QRect(120, 295, 231, 21))
        self.aduserName_lineEdit.setText("")
        self.aduserName_lineEdit.setObjectName("aduserName_lineEdit")
        self.aduserName_label = QtWidgets.QLabel(RegisterWindow)
        self.aduserName_label.setGeometry(QtCore.QRect(40, 296, 81, 20))
        self.aduserName_label.setObjectName("aduserName_label")
        self.adpassword_lineEdit = QtWidgets.QLineEdit(RegisterWindow)
        self.adpassword_lineEdit.setGeometry(QtCore.QRect(120, 345, 231, 21))
        self.adpassword_lineEdit.setText("")
        self.adpassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.adpassword_lineEdit.setObjectName("adpassword_lineEdit")
        self.adpassword_label = QtWidgets.QLabel(RegisterWindow)
        self.adpassword_label.setGeometry(QtCore.QRect(40, 346, 81, 20))
        self.adpassword_label.setObjectName("adpassword_label")

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Form"))
        self.confirm_pushButton.setText(_translate("RegisterWindow", "确认"))
        self.userName_label.setText(_translate("RegisterWindow", "用户名"))
        self.cancel_pushButton.setText(_translate("RegisterWindow", "取消"))
        self.password_label.setText(_translate("RegisterWindow", "密  码"))
        self.repassword_label.setText(_translate("RegisterWindow", "确认密码"))
        self.adress_label.setText(_translate("RegisterWindow", "住  址"))
        self.phone_label.setText(_translate("RegisterWindow", "联系电话"))
        self.aduserName_label.setText(_translate("RegisterWindow", "管理员账户"))
        self.adpassword_label.setText(_translate("RegisterWindow", "管理员密码"))
